#!/bin/bash

# Description:	Dotfile installer
# Author:	Marcelo JP Alcocer (marcelo.j.p.alcocer@gmail.com)
# Date:		2019.09.28

# Dotfile base directory
dotbasedir="$(dirname $(realpath $0))"

# Symlink function
dotln(){
	for dotfile in "${!dotdests[@]}"; do ln -sf "${dotdir}/${dotfile}" "${dotdests[${dotfile}]}"; done
}

# sh dotfiles
dotdir="${dotbasedir}/sh"
declare -A dotdests=(
	["aliases"]="${HOME}/.aliases"
	["env"]="${HOME}/.env"
	["functions"]="${HOME}/.functions"
	["inputrc"]="${HOME}/.inputrc"
	["logout"]="${HOME}/.logout"
	["profile"]="${HOME}/.profile"
	["rc"]="${HOME}/.rc"
)
dotln

# bash dotfiles
dotdir="${dotbasedir}/sh/bash"
declare -A dotdests=(
	["aliases"]="${HOME}/.bash_aliases"
	["env"]="${HOME}/.bash_env"
	["functions"]="${HOME}/.bash_functions"
	["logout"]="${HOME}/.bash_logout"
	["rc"]="${HOME}/.bashrc"
)
dotln

# zsh dotfiles
dotdir="${dotbasedir}/sh/zsh"
declare -A dotdests=(
	["aliases"]="${HOME}/.zsh_aliases"
	["env"]="${HOME}/.zsh_env"
	["functions"]="${HOME}/.zsh_functions"
	["logout"]="${HOME}/.zlogout"
	["rc"]="${HOME}/.zshrc"
)
dotln

# Vim dotfiles
dotdir="${dotbasedir}/vim"
declare -A dotdests=(
	["rc"]="${HOME}/.vimrc"
	["custom-misc.utf-8.add"]="${HOME}/.vim/spell/"
	["custom-python.utf-8.add"]="${HOME}/.vim/spell/"
	["en.utf-8.add"]="${HOME}/.vim/spell/"
	["sv.utf-8.add"]="${HOME}/.vim/spell/"
)
dotln

# Git dotfiles
dotdir="${dotbasedir}/git"
declare -A dotdests=(
	["config"]="${HOME}/.gitconfig"
)
dotln

# Python dotfiles
dotdir="${dotbasedir}/python"
declare -A dotdests=(
	["yapf.ini"]="${HOME}/.config/yapf/yapf.ini"
)
dotln

# VSCode dotfiles
dotdir="${dotbasedir}/vscode"
declare -A dotdests=(
	["keybindings.json"]="${HOME}/.config/Code - OSS/User/"
	["settings.json"]="${HOME}/.config/Code - OSS/User/"
	["snippets"]="${HOME}/.config/Code - OSS/User/"
)
dotln
